### ISSUE TITLE
Error webhook

### ISSUE THREAD

**Issue by cpgo** [metacontroller/metacontroller#195] opened 2021-02-18 20:05 UTC
As far as I could find on the docs there is not way to capture the underlying k8s client error messages besides watching the metacontroller logs.

Would it make sense to have an `error` webhook where we could send the error messages to?

**Comment by grzesuav** [comment] 2021-02-18 21:32
hi @cpgo , idea is, firstly, to enable events in metacontroller itself (so when you do `kubectl describe parentResource` you will see event related to that) - related issue is https://github.com/metacontroller/metacontroller/issues/170

**Comment by grzesuav** [comment] 2021-02-18 21:34
and secondly - to extend `sync`/`finalize` and `customize` endpoints to report also events from controllers, but want to implement mechanism to populate events from metacontroller itself first.

**Comment by cpgo** [comment] 2021-02-18 22:48
Very cool. I didn't see that issue, It seems to be exactly what I need.

Have you started writing this feature yet or already have an idea on how to write it?

I'm not familiar with the project codebase but if I can help you with anything feel free to ping me.

**Comment by grzesuav** [comment] 2021-02-19 20:52
Unfortunately, not yet. I have couple of PR's open (regarding testing and refactoring) want to get it merged first. The idea is to use https://github.com/kubernetes/client-go/tree/v0.17.17/tools/events package, but need to do some discovery how to do it in efficient way.

**Comment by grzesuav** [comment] 2021-02-19 20:53
I will close this issue as duplicate of https://github.com/metacontroller/metacontroller/issues/170, please continue discussion there, cheers :)

**Closed by grzesuav** 2021-02-19 20:53 UTC
