### ISSUE TITLE
Ingresses recreated instead of updating in place when changing ingress apiVersion on CompositeController

### ISSUE THREAD

**Issue by AnaVomvylas** [metacontroller/metacontroller#753] opened 2023-02-14 14:04 UTC
When changing the ingress apiVersion from `extensions/v1beta1` to `networking.k8s.io/v1`, I expected no interruption on the ingresses. 
What actually happened instead, is that current running ingresses were deleted and new ones were recreated in their place. Some of them (~13%) were updated in place instead of being recreated, which indicates weird behaviour. 

Here is the yaml diff of the compositeController resource (with names changed)
```diff
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: my-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: myApiVersion/v1
    resource: myResource
  childResources:
    - apiVersion: apps/v1
      resource: deployments
      updateStrategy:
        method: InPlace
    - apiVersion: v1
      resource: services
      updateStrategy:
        method: InPlace
-   - apiVersion: extensions/v1beta1
+   - apiVersion:  networking.k8s.io/v1
      resource: ingresses
      updateStrategy:
        method: InPlace
    - apiVersion: policy/v1beta1
      resource: poddisruptionbudgets
      updateStrategy:
        method: InPlace
    - apiVersion: autoscaling/v1
      resource: horizontalpodautoscalers
      updateStrategy:
        method: InPlace
    - apiVersion: cloudformation.linki.space/v1alpha1
      resource: stacks
      updateStrategy:
        method: InPlace
  hooks:
    sync:
      webhook:
        url: http://my-controller.myNamespace/sync
```

and here is the golang code diff on myController webhook for the ingresses:
```diff
	return &Ingress{
-		TypeMeta:   typeMeta("extensions/v1beta1", "Ingress"),
+		TypeMeta:   typeMeta("networking.k8s.io/v1", "Ingress"),
		ObjectMeta: objectMeta,
-		Spec: extensionsv1beta1.IngressSpec{
-			Backend: &extensionsv1beta1.IngressBackend{
-				ServiceName: i.name,
-				ServicePort: intstr.FromString("http"),
+		Spec: networkingv1.IngressSpec{
+			DefaultBackend: &networkingv1.IngressBackend{
+				Service: &networkingv1.IngressServiceBackend{
+					Name: i.name,
+					Port: networkingv1.ServiceBackendPort{
+						Name: "http",
+					},
+				},
			},
		},
```

I am trying to better understand why this happened, especially considering that some ingresses were updated in place and others were replaced.
Version of metacontroller was 0.4.5, but I replicated the issue with the latest 4.7.4 version as well.
Kubernetes version is 1.21, running on AWS EKS

**Comment by grzesuav** [comment] 2023-02-16 16:33
seems related to what was already reported - https://github.com/metacontroller/metacontroller/issues/437

**Comment by grzesuav** [comment] 2023-04-08 15:36
closing as duplicate of #437

**Closed by grzesuav** 2023-04-08 15:36 UTC
Labels: bug, duplicate
