### ISSUE TITLE
[Feature request] API to immediately run sync

### ISSUE THREAD

**Issue by timdevlet** [metacontroller/metacontroller#675] opened 2022-09-22 14:27 UTC
Hello. I have a thousand deployments. Can we add a HTTP server that runs a sync state immediately? I attached a draft. And I have one crucial question. Is it safe to invoke p.Start() at any time? 

We don't want to wait for 10s / 5s. It is very critical to start sync as fast as possible. 

metacontroller/pkg/server/server.go
```
// New returns a new controller manager and a function which can be used
// to release resources after the manager is stopped.
func New(configuration options.Configuration) (controllerruntime.Manager, error) {
	// Create informer factory for metacontroller API objects.
	mcClient, err := mcclientset.NewForConfig(configuration.RestConfig)
	if err != nil {
		return nil, fmt.Errorf("can't create client for api %s: %w", v1alpha1.SchemeGroupVersion, err)
	}

       ......
	
	// Add http router to call /sync
	httpRouter := HttpRouter{compositeReconciler, decoratorReconciler}
	go func(httpRouter *HttpRouter) {
		port := ":" + configuration.TriggerSyncPort
		logging.Logger.Info("Api server starting.", "port", port)
		http.HandleFunc("/sync", httpRouter.triggerSync)
		err := http.ListenAndServe(port, nil)
		if err != nil {
			logging.Logger.Error(err, "Cannot start Api server")
		}
	}(&httpRouter)

	return mgr, nil
}

type HttpRouter struct {
	compositeReconciler *composite.Metacontroller
	decoratorReconciler *decorator.Metacontroller
}

func (r *HttpRouter) triggerSync(w http.ResponseWriter, req *http.Request) {
	logging.Logger.Info("New /sync request")
	for _, pController := range r.compositeReconciler.ParentControllers {
		pController.Start()
	}

	for _, dController := range r.decoratorReconciler.DecoratorControllers {
		dController.Start()
	}

	w.Header().Set("Content-Type", "application/json")
	fmt.Fprintf(w, "ok")
}
```

**Comment by grzesuav** [comment] 2022-10-14 12:43
https://github.com/metacontroller/metacontroller/issues/43

**Comment by grzesuav** [comment] 2022-10-14 12:44
1. I think those method was intended to run once, unsure if running them many times won't cause any issues
2. It will always be a few second delay, the cache needs to be populated from API server anyway

**Comment by grzesuav** [comment] 2023-11-16 19:28
Closing as duplicate of https://github.com/metacontroller/metacontroller/issues/43

**Closed by grzesuav** 2023-11-16 19:28 UTC
